"""Updated models for new database URL

Revision ID: 133936ad7631
Revises: 6b0d4ba6f912
Create Date: 2025-02-28 16:23:00.100984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133936ad7631'
down_revision: Union[str, None] = '6b0d4ba6f912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_patient_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_doctor_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'staff', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('patients_user_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payments_patient_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('prescriptions_doctor_id_fkey', 'prescriptions', type_='foreignkey')
    op.drop_constraint('prescriptions_medicine_id_fkey', 'prescriptions', type_='foreignkey')
    op.drop_constraint('prescriptions_patient_id_fkey', 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'staff', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('staff_user_id_fkey', 'staff', type_='foreignkey')
    op.create_foreign_key(None, 'staff', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_foreign_key('staff_user_id_fkey', 'staff', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key('prescriptions_patient_id_fkey', 'prescriptions', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key('prescriptions_medicine_id_fkey', 'prescriptions', 'medicines', ['medicine_id'], ['id'])
    op.create_foreign_key('prescriptions_doctor_id_fkey', 'prescriptions', 'staff', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_patient_id_fkey', 'payments', 'patients', ['patient_id'], ['id'])
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_user_id_fkey', 'patients', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'staff', ['doctor_id'], ['id'])
    op.create_foreign_key('appointments_patient_id_fkey', 'appointments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
