"""Add support tickets and property image URL

Revision ID: 8b7347177b47
Revises: 06c66f8d574e
Create Date: 2025-02-27 14:50:18.047274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7347177b47'
down_revision: Union[str, None] = '06c66f8d574e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_id'), 'medical_history', ['id'], unique=False)
    op.add_column('medicines', sa.Column('manufacturer', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('medicines', sa.Column('batch_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.add_column('prescriptions', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('prescriptions', sa.Column('frequency', sa.String(), nullable=True))
    op.alter_column('reports', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('staff', sa.Column('title', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('qualifications', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('staff', 'qualifications')
    op.drop_column('staff', 'specialization')
    op.drop_column('staff', 'title')
    op.alter_column('reports', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('prescriptions', 'frequency')
    op.drop_column('prescriptions', 'instructions')
    op.drop_column('payments', 'payment_date')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('patients', 'emergency_contact')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'gender')
    op.drop_column('medicines', 'batch_number')
    op.drop_column('medicines', 'expiry_date')
    op.drop_column('medicines', 'manufacturer')
    op.drop_index(op.f('ix_medical_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
